# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example Corne-ish Zen Custom'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '[
        "corneish_zen_v1_left","corneish_zen_v1_right",
        "corneish_zen_v2_left","corneish_zen_v2_right"
      ]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y\nCONFIG_ZMK_MOUSE=y"]'
      branches: '["petejohanson/zmk/feat/pointers-move-scroll","zmkfirmware/zmk/main petejohanson/zmk/feat/pointers-move-scroll"]'
